name: OctoBot Python Notify reusable workflow

on:
  workflow_call:
    secrets:
      DISCORD_GITHUB_WEBHOOK:
        required: true

jobs:
  notify:
    name: Notify
    runs-on: ubuntu-latest
    steps:
      - name: Notify discord
        uses: sarisia/actions-status-discord@v1
        with:
          status: Failure
          webhook: ${{ secrets.DISCORD_GITHUB_WEBHOOK }}
