name: OctoBot Python3 Tests reusable workflow

on:
  workflow_call:
    inputs:
      project_test_dirs:
        description: 'Project test dirs'
        type: string
        default: 'tests'
      python_version:
        description: 'Python version to use'
        type: string
        default: '3.10.x'
      python_arch:
        description: 'Python arch to use'
        type: string
        default: 'x64'
    secrets:
      COVERALLS_REPO_TOKEN:
        required: false
      http_proxy:
        required: false
      https_proxy:
        required: false

jobs:
  tests:
    name: ${{ matrix.os }} - Python - ${{ matrix.type }} - tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest, windows-latest, ubuntu-latest ]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python_version }}
          architecture: ${{ inputs.python_arch }}

      - name: Install dependencies
        run: pip install -r dev_requirements.txt -r requirements.txt

      - name: Pytests
        run: pytest --cov=. --cov-config=.coveragerc --durations=0 -rw ${{ inputs.project_test_dirs }}

      - name: Publish coverage
        if: github.event_name == 'push'
        run: coveralls
        continue-on-error: true
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
